spring:
  application:
    name: mars-payment-node

  security:
    oauth2:
      client:
        provider:
          marspay-authorization-server:
            token-uri: http://localhost:9000/oauth2/token

        registration:
          relay-client:
            provider: marspay-authorization-server
            client-id: mars-payment-node
            client-secret: ${MARSPAY_MARS_CLIENT_SECRET:mars-secret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            scope:
              - relay.submit

      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          audiences:
            - mars-payment-node
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml