package io.github.lukasz756.marspay.paymentnode.payment;

public enum PaymentOperationType {
    CREATE,

    AUTHORIZATION_REQUESTED,
    AUTHORIZATION_CONFIRMED,
    AUTHORIZATION_DECLINED,

    CAPTURE_REQUESTED,
    CAPTURE_CONFIRMED,
    CAPTURE_FAILED,

    CANCEL_REQUESTED,
    CANCEL_CONFIRMED,
    CANCEL_FAILED,

    REFUND_REQUESTED,
    REFUND_CONFIRMED,
    REFUND_FAILED
}
